### ISSUE TITLE
Multiple tree views don't work

### ISSUE THREAD

**Issue by OLiviER-808s** [MatijaNovosel/vue-tree-view#3]
I have 3 treeviews on the same page with 3 arrays for each of the results and all 3 arrays are being populated whenever I select an option on any of the tree views. It would be much easier to work with if only the array set as the v-model on a particular tree view component was updated when the user selected an option.

**Comment by MatijaNovosel** [comment]
Try updating to version 0.0.13, I added some fixes to the component. If not, I'll look into it.

**Comment by OLiviER-808s** [comment]
Already using 0.0.13 and the issue is still present

**Comment by MatijaNovosel** [comment]
Should be fixed now, upgrade to version 0.0.15. The issue was that there are multiple event buses in the component with the same identifier which triggered updates on the tree view the event bus didn't belong to.
