### ISSUE TITLE
When a child checkbox is selected then de-selected, all other child checkboxes become selected

### ISSUE THREAD

**Issue by OLiviER-808s** [MatijaNovosel/vue-tree-view#4]
Here is a video

https://github.com/MatijaNovosel/vue-tree-view/assets/72664971/8fe8e592-f458-4f82-a3fc-1493eb90b64d

**Comment by MatijaNovosel** [comment]
Can you give me a reproducible example with code please? I can't seem to recreate this bug - I've added more updates in the meantime, namely in the 1.1.0 version.
