### ISSUE TITLE
Changes in v-model values are not reflected

### ISSUE THREAD

**Issue by sam61086** [MatijaNovosel/vue-tree-view#5]
when the model value is changed in javascript, the tree will not change and is still original status.
<template>
<tree-view
      color="blue"
      :items="treeViewItems"
      v-model="treeViewSelection"
      dense
      open-all
    /> 
</template>
<script setup>
let treeViewSelection = ref([]);
function test() {
  treeViewSelection.value = []
}

**Comment by MatijaNovosel** [comment]
Fixed in version `1.3.0`, try updating the package and seeing if it works.

**Comment by sam61086** [comment]
Yes it works in 1.3.0, thanks!
